name: complex-plot-bot

on: 
  push:
    branches: [main]
  #schedule:
  #- cron: '*/5 * * * *' # runs every 5 min
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # install the latest python version
        
      - name: Install TeXLive
        run: |
          sudo apt-get install texlive -y
          tlmgr init-usertree
          tlmgr repository add ftp://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2019/tlnet-final
          sudo apt-get install xzdec
          tlmgr --verify-repo=none install framed
          tlmgr --verify-repo=none install standalone
          
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: execute py script 
        env: 
          API_KEY: ${{secrets.API_KEY}}
          API_KEY_SECRET: ${{secrets.API_KEY_SECRET}}
          ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
          ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
        run: python bot.py
