name: complex-plot-bot

on: 
#   push:
#     branches: [main]
    schedule:
      - cron: '30 7,13,19 * * *' # “At minute 30 past hour 9, 15, and 21.” 
#     - cron: '*/5 * * * *' # “Every 5 minutes.” 
#   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # install the latest python version
        
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Install TeXLive
        run: |
          sudo apt-get install texlive
          sudo apt-get install texlive-fonts-extra
          sudo apt-get install dvipng   
          
      - name: execute py script 
        env: 
          API_KEY: ${{secrets.API_KEY}}
          API_KEY_SECRET: ${{secrets.API_KEY_SECRET}}
          ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
          ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
        run: python bot.py
